### PR TITLE
Combine Pixels Into Polygons

### LINKED ISSUE #88: A small break between pixels
Small breaks in pixels sometimes appear:
image
 
image
This glitch occurs with both the ttf and otf version, but it's more severe in the ttf

Haven't tested it on other platforms, but I am using Linux, X11 and gnome specifically with proprietary NVIDIA drivers

### PR DESCRIPTION
**Pull request by Dheatly23**
This PR fixes #88 by combining pixels into polygons.

### CODE REVIEW

**Comment by Ciubix8513** [comment]
There seems to be an issue with some glyphs:
image
image
While I don't think it will cause any issues with the font rendering, it's still a bug

**Comment by Dheatly23** [comment]
Yeah, to handle holes, i basically put a tiny cut in the outer polygon, then splice the hole in. There may be better solution though. The hole polygonizer algorithm is still there, just need to rework how to put it back in.

**Comment by Dheatly23** [comment]
Okay i fixed it. Turns out, i just need to emit the inner polygon to be recognized as holes. Fingers crossed that font renderers can handle that.

**Comment by Ciubix8513** [comment]
Now there's another issue, for some reason the glyphs Ф ф broke:
image
image
I don't think I have enough python knowledge to help fix it

**Comment by Dheatly23** [comment]
Huh, i tested it and it seems like some weird interaction with mutating iterator variable. I'll push the fix soon.

**Comment by dantaeusb** [comment]
My apologies for being a little off-topic, but I am super fascinated by this.
Is there a common name for the algorithm you've used?

- I see it first creates 1 byte matrix by using flood fill, to create “layers” of rectangles with the lowest bit (later referenced `CellFlag.ACTIVE`);
- Then I assume you're writing directions to the upper 4 bits of that matrix in `doMove` for the whole layer (outer_poly);
- Then the same applied to all inner “holes”, creating inner vectors (inner_poly), (there was probably the "ф" problem);
- Those lines then yield to the pen.

My question is how exactly the length is figured out, as the output of `doMove` called line. I can't really wrap my head around where this matrix turns to points because from the first glance, there's no recursive calls or some traversing when those directional flags are set.

I would be super happy to know more about this if you don't mind. You can use email in my profile if you would rather not explain here.

Thanks!

**Comment by Dheatly23** [comment]
Thanks for the (very late) response, hope your vacation is okay!

As far as my knowledge goes, there seem to be no one else that do it the same way. I'll explain what the algorithm does:
1. Split the image into connected parts (the `segmentize` function). Two pixels are connected if they share an edge or corner.
2. Now the segmented parts **only** contains 2 bundaries, outer and possibly inner. So it will make the calculation easier.
3. To trace the boundary, i use a "turtle" that hugs the boundary from right (right side is filled, left side is empty). The turtle is initally on the top-leftmost pixel facing right.
4. To make the turtle movement more efficient, in the `doMove` function i check on neighboring pixels where the turtle at to plan it's movement. There are 9 cases to be considered.
5. While the turtle is moving, i record every corner that the turtle made.
6. The turtle is done travelling whenever it goes back to it's original point (this took so long to tweak). Remove the extra path beyond that point.
7. And for the internal boundary do the same, making sure the turtle is moving opposite of outer loop.
8. (Optionally) i tried to simplify even further by splicing the inner loop to outer loop, but apparently this may cause issues. Maybe in the future it may be implemented better.

The cell data is a bitflag with values as follows:
- Bit 0: Cell is filled
- Bit 4: Cell has wall at top
- Bit 5: Cell has wall at bottom
- Bit 6: Cell has wall at left
- Bit 7: Cell has wall at right

The filled bit is obvious. The wall bits are used to find inner boundaries that has not been found (if it should have wall but isn't set). I don't know what you mean by length, i don't use length in the algorithm, only direction of the turtle is considered.

And that problem with ф is apparently Python does not like mutating iterator variable while it is iterating. I never experienced this issue until now, but currently i restore the inner value every time the inner polygon generation is done. Maybe it's my bug, but so far that fixes it.

**Comment by IdreesInc** [comment]
Apologies for the delay in reviewing this, had the flu, not fun. Thanks @Ciubix8513 for reviewing it in the meantime and discovering those bugs!
But wow this is brilliant. Thank you @Dheatly23 for putting the time and effort into solving this problem, I didn't realize how nontrivial it would turn out to be. I especially appreciate the comments that illustrate how the outlines are being built. Going to merge this into a branch first so that I can update the version number, then will get a release out later today!

**Comment by dantaeusb** [comment]
FYI I noticed a detail when installing new version of the font, I believe these margin alignments are (leftMargin from 44034119d788630c41590cf549fc6dfd8f16d200) are no longer applied.

Screenshot 2023-02-05 at 23 25 08


P.S. I also extended symbols with european-nonlatin set: https://github.com/dantaeusb-mc/Minefont/blob/main/src/characters.json, but it's auto-generated, and I'm still working on it. I want to get non-monospaced version too.

**Comment by Dheatly23** [comment]
Oh yeah, i didn't see that left margin can be non-integer. I just assumed it is and shift the entire image. I think i did the same with descent and diacritic space too. Oh well, that could be fixed later. Thanks anyway for accepting my PR.

**Pull request merged**
