### PR TITLE
Add ligatures for colon colon and period period

### PR DESCRIPTION
**Pull request by maddymakesgames**
Added ligatures for `::` and `..`, these are commonly used character pairs in Rust.

Without ligatures these character sequences are pretty wide
before_ligature

With them they are more condensed and leave more room for the important parts of the code
after_ligature

### CODE REVIEW

**Comment by joshudson** [comment]
Doesn't this defeat the purpose of being a monspaced font?

**Comment by maddymakesgames** [comment]
yeah but most ligatures already aren't monospace so I don't think that matters?

**Comment by WexCore** [comment]
Already existing ligatures take the same space as the symbols they replace.
Like "⇒" take the same 2 symbols of space as "=>"
Yours seems not to follow the same pattern and it needs to be fixed, I guess.

**Comment by IdreesInc** [comment]
Thank you for taking the time to create new ligatures! Unfortunately since ligatures must be monospaced as well, we are stuck in a weird situation where you have to use small pixels and leave a lot of whitespace. For glyphs made of dots like . and :, ligatures might not look great in this situation.

**Pull request closed without merging**
