### PR TITLE
Extend characters with European non-latin set

### PR DESCRIPTION
**Pull request by dantaeusb**
This pull request contains all implemented european non-latin letters, without margins.

While definitions seem correct to me, with the current shape implementation, there are few issues to fix alongside:

#### 1. Characters longer than 5px are overlapping other characters.

Examples with Georgian and Armenian scripts:
Screenshot 2023-02-05 at 23 55 00
Screenshot 2023-02-05 at 23 55 07
Screenshot 2023-02-05 at 23 55 03
Screenshot 2023-02-05 at 23 55 09

#### 2. Descent pixels, which are lower than 7px border, seem to be cut off, even with correct descent parameter:

kart-issue

### CODE REVIEW

**Comment by dantaeusb** [comment]
I believe it addresses the #41, #75. Though for Hebrew, some adjustments might be useful.

A couple of letters seem to be off, for example ע

Screenshot 2023-02-06 at 00 15 06

**Comment by dantaeusb** [comment]
Also, Cyrillic ц is misaligned, missing descent: 1

Screenshot 2023-02-06 at 01 30 40

**Comment by dantaeusb** [comment]
Results I was able to achieve on non-monospaced font (all webkit, macOS Chrome):

With smoothing, 16px
Screenshot 2023-02-06 at 03 44 04

No smoothing, 16px
Screenshot 2023-02-06 at 03 44 13

No smoothing, 8px (original size)
Screenshot 2023-02-06 at 03 44 30

Some notable details:

Using bearings instead of extra pixel in fixed width:
```python
monocraft[character["name"]].left_side_bearing = math.floor(PIXEL_SIZE / 2)
monocraft[character["name"]].right_side_bearing = math.floor(PIXEL_SIZE / 2)
```
Which works surprisingly well. Though, probably won't help to fit more into long letters. But margins could.

The cut-off of the descent pixels could be either macOS preview bug, or miscalculated size.
For size to work properly, I found those parameters to work the best:
```python
monocraft.design_size = 8
monocraft.em = math.floor(PIXEL_SIZE * 7.75)
```

**Comment by IdreesInc** [comment]
Coming back to this, once again amazed at the number of glyphs added to the glyphset. I've looked through them from an english-speaking perspective and see no obvious bugs, but I am going to release this as a "beta" for a few days and see if anyone see's anything off. Thank you once again for the work you have put into this, it is very much appreciated.

**Pull request merged**
