### PR TITLE
Adds Bold, Italic, and Thin Variants

### PR DESCRIPTION
**Pull request by Dheatly23**
Implements #127. Still needs to fix lag somehow. And maybe package all variants in a single file?

Example:
(size: 10 pt)
(in order: Regular, Italic, Bold, Bold Italic):
Example

### CODE REVIEW

**Comment by Ciubix8513** [comment]
Font generation can be really slow, especially now with continuous ligatures, and this will slow it down 3x, if I understand the code. Maybe it would be a good idea to separate each variant generation into it's own thread? So that the slow down is not that bad.

I don't have much experience with python, but form what I found it seems to be relatively easy

**Comment by Dheatly23** [comment]
It gets a bit better with manually transforming bold glyph. But now there is really nasty segfault which i can't fix. I've commented out the offending line for now.

**Comment by LevitatingBusinessMan** [comment]
Very cool! What are the current issues that still need to be fixed?

**Comment by Dheatly23** [comment]
Boldness needs to be ajdusted, i'm still trying to find a middle point. And i didn't test for all character, some might gets unreadable with bold. Also i don't know if putting all fonts into `.ttc` is a good move, maybe some OS does not support it? Lastly generation time is getting even longer, but it can be deferred for another time.

**Comment by LevitatingBusinessMan** [comment]
I've tried it out. For my usecase, in the terminal, the bold might be _too_ thick.

Which conflicts with @SirMishaa's opinion who thinks it needs to be thicker.

**Comment by Dheatly23** [comment]
I can make it multiple level of boldness/thinness. Trouble is, build time multiplies with each new variant.

**Comment by LevitatingBusinessMan** [comment]
I don't think build time is that much of an issue. My laptop compiles your branch in 30 seconds, and most people download the font pre-built. I am curious what @IdreesInc's opinion is on that.

**Comment by Ciubix8513** [comment]
I personally agree, while long build times are annoying when you're trying to quickly iterate on a glyph(s) for most people it's not an issue. Maybe add a flag to disable generation of additional fonts, to allow to iterate faster? if that's the concern.

**Comment by IdreesInc** [comment]
> I don't think build time is that much of an issue. My laptop compiles your branch in 30 seconds, and most people download the font pre-built. I am curious what @IdreesInc's opinion is on that.

Look, if the font you use doesn't take a few days to generate, is it even a real font?

**Comment by IdreesInc** [comment]
Wow, this is fantastic, thanks @Dheatly23  for adding this in! Apologies for the delay in reviewing it, been working on many new projects at once and haven't had the time to review new features in stable projects until now. 
The new weights look great, though the very bold and very light ones are hard to read on my machine (as expected). I've noticed that the font looks different based on the whether the user is on Windows or Mac due to the font rendering, so having new weights would likely reduce a lot of the complaints Monocraft receives. My only question is why do we need italic variants? At least on my Mac, the font is italicized automatically, though maybe this doesn't occur on other machines?

**Comment by Dheatly23** [comment]
Thanks for the review!

I made a few tweaks with the polygonizer algorithm to support bold/thin, so there _may be_ some bugs. And i'm still not happy with thinning algorithm (example: how to thin across corner?), but for now it's not too bad. One optimization (removing segmentation) significantly speeds up the code.

About the italic, some font renderer apparently can't automatically italicize fonts. So i suppose adding separate italic file would fix that.

With boldness of black variant, i reduce it a bit just now. You can see it here (8 pts, Windows 10):
Black Before After
I'm worried it's a _bit_ too close to other variants, so feedback is much appreciated!

**Comment by IdreesInc** [comment]
The weights look good to me on the mac (though the super light weight doesn't connect, but not much that can be done there). Will check out on my Windows machine when I get home and hopefully get this PR merged this weekend! Also love the concept of the .ttc thing, never realized you could bundle font files that way. Any idea if that will work on Windows/Linux as well?

**Pull request merged**
