### PR TITLE
Add all Czech characters to sfd

### PR DESCRIPTION
**Pull request by Akxe**

### CODE REVIEW

**Comment by IdreesInc** [comment]
This is amazing, I apologize for not getting to this sooner. Currently in the process of reviewing this PR. As it has a lot of changes, will need to take some time to ensure everything matches correctly with the Minecraft versions.

**Comment by IdreesInc** [comment]
Seems like some of the characters are not the same as the ones in Minecraft. I will make note of the characters that you have added and modify them to match sometime soon (though it might have to be in a separate PR).

**Comment by Akxe** [comment]
That is definitely true. Many of Czech characters are not present in Minecraft at all.

Ask me anything if you need help to clarify something.

**Comment by IdreesInc** [comment]
Thanks once more for your help! Monocraft is now script based so I had to add all of the characters here in code form. I believe that I have added the entire Czech alphabet as shown on [Wikipedia](https://en.wikipedia.org/wiki/Czech_orthography), but please feel free to raise another issue if something is missing!

**Pull request closed without merging**
