### PR TITLE
Added Turkish letters

### PR DESCRIPTION
**Pull request by evrifaessa**
Following #15, I've added Turkish-specific characters.

image

It's my first time using FontForge, please check if I've done something wrong before merging it. I also haven't updated the previews, I'd be glad if you can.

### CODE REVIEW

**Comment by evrifaessa** [comment]
image

**Comment by evrifaessa** [comment]
Oh, a rewrite. Should I remake the PR? @IdreesInc

**Comment by IdreesInc** [comment]
If you could, that'd be greatly appreciated. Otherwise leave it and at some point I should be able to get to it in a separate PR

**Comment by eminarican** [comment]
@evrifaessa original 

> Following #15, I've added Turkish-specific characters.
> 
> image
> 
> It's my first time using FontForge, please check if I've done something wrong before merging it. I also haven't updated the previews, I'd be glad if you can.

are "Ş" and "ş" letters' extensions identical to how is it in minecraft? or it's just because the editor doesn't show the entire letter?
unknown-2

**Comment by evrifaessa** [comment]
> @evrifaessa
> 
> > Following #15, I've added Turkish-specific characters.
> > image
> > It's my first time using FontForge, please check if I've done something wrong before merging it. I also haven't updated the previews, I'd be glad if you can.
> 
> are "Ş" and "ş" letters' extensions identical to how is it in minecraft? or it's just because the editor doesn't show the entire letter? unknown-2

Minecraft's original font doesn't have Turkish characters. The preview in the editor doesn't show the full glyph.

**Comment by eminarican** [comment]
> > @evrifaessa
> > > Following #15, I've added Turkish-specific characters.
> > > image
> > > It's my first time using FontForge, please check if I've done something wrong before merging it. I also haven't updated the previews, I'd be glad if you can.
> > 
> > 
> > are "Ş" and "ş" letters' extensions identical to how is it in minecraft? or it's just because the editor doesn't show the entire letter? unknown-2
> 
> Minecraft's original font doesn't have Turkish characters. The preview in the editor doesn't show the full glyph.

nope it does have turkish characters you could check it from textures under fonts/accented.png, take a look
https://github.com/InventivetalentDev/minecraft-assets/blob/1.19.2/assets/minecraft/textures/font/accented.png

**Comment by IdreesInc** [comment]
I sincerely appreciate the effort that went into this PR, but I am going to close it for now as we need to ensure that all new glyphs match their Minecraft counterparts. Feel free to make another PR in the future including the updated glyphs!

**Comment by koply** [comment]
that disrespect tho lol

Screenshot_1

**Pull request closed without merging**
